{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdcf56e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "def scrape_justdial():\n",
    "    with sync_playwright() as p:\n",
    "\n",
    "        # Launch browser\n",
    "        browser = p.chromium.launch(\n",
    "            headless=False,      # Keep False while debugging\n",
    "            slow_mo=100\n",
    "        )\n",
    "\n",
    "        # Create browser context\n",
    "        context = browser.new_context(\n",
    "            viewport={\"width\": 1366, \"height\": 768},\n",
    "            user_agent=\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36\",\n",
    "            locale=\"en-US\"\n",
    "        )\n",
    "\n",
    "        page = context.new_page()\n",
    "\n",
    "        page.set_default_navigation_timeout(120000)\n",
    "        page.set_default_timeout(120000)\n",
    "\n",
    "        try:\n",
    "            print(\"Opening Justdial...\")\n",
    "\n",
    "            page.goto(\n",
    "                URL,\n",
    "                wait_until=\"domcontentloaded\",\n",
    "                timeout=120000\n",
    "            )\n",
    "\n",
    "            page.wait_for_timeout(5000)\n",
    "\n",
    "            print(\"Page Title:\")\n",
    "            print(page.title())\n",
    "\n",
    "            # Scroll to load more results\n",
    "            for i in range(5):\n",
    "                page.mouse.wheel(0, 3000)\n",
    "                page.wait_for_timeout(3000)\n",
    "\n",
    "            print(\"Current URL:\", page.url)\n",
    "\n",
    "            # Save HTML\n",
    "            html = page.content()\n",
    "\n",
    "            with open(\"justdial.html\", \"w\", encoding=\"utf-8\") as f:\n",
    "                f.write(html)\n",
    "\n",
    "            print(\"HTML saved successfully.\")\n",
    "\n",
    "            # Save Screenshot\n",
    "            page.screenshot(path=\"justdial.png\", full_page=True)\n",
    "            print(\"Screenshot saved.\")\n",
    "\n",
    "        except TimeoutError:\n",
    "            print(\"Navigation timed out.\")\n",
    "\n",
    "        except Exception as e:\n",
    "            print(\"Error:\", e)\n",
    "\n",
    "        finally:\n",
    "            browser.close()\n",
    "\n",
    "\n",
    "if _name_ == \"_main_\":\n",
    "    scrape_justdial()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
